java_library(
    name = "emissions",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = [
        "//src/yuca/src/main/java/yuca/util",
        "//src/yuca/src/main/proto/yuca/signal:signal_java_protos",
    ],
    resources = ["//src/yuca/src/main/resources/emissions:emissions_data"],
)
