java_library(
    name = "util",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = [
        "//src/yuca/src/main/proto/yuca/signal:signal_java_protos"
    ],
    resources = ["//src/yuca/src/main/c/yuca/util:libtime.so"],
)
