# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: signal.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'signal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csignal.proto\x12\x0byuca.signal\"\xc9\x03\n\x0eSignalInterval\x12\x39\n\x05start\x18\x01 \x01(\x0b\x32%.yuca.signal.SignalInterval.TimestampH\x00\x88\x01\x01\x12\x37\n\x03\x65nd\x18\x02 \x01(\x0b\x32%.yuca.signal.SignalInterval.TimestampH\x01\x88\x01\x01\x12\x34\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32&.yuca.signal.SignalInterval.SignalData\x1a\x45\n\tTimestamp\x12\x11\n\x04secs\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x12\n\x05nanos\x18\x02 \x01(\x04H\x01\x88\x01\x01\x42\x07\n\x05_secsB\x08\n\x06_nanos\x1a\xb3\x01\n\nSignalData\x12\x41\n\x08metadata\x18\x01 \x03(\x0b\x32/.yuca.signal.SignalInterval.SignalData.Metadata\x12\x12\n\x05value\x18\x02 \x01(\x01H\x00\x88\x01\x01\x1a\x44\n\x08Metadata\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05value\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_nameB\x08\n\x06_valueB\x08\n\x06_valueB\x08\n\x06_startB\x06\n\x04_end\"\x80\x02\n\x06Signal\x12+\n\x04unit\x18\x01 \x01(\x0e\x32\x18.yuca.signal.Signal.UnitH\x00\x88\x01\x01\x12\x0e\n\x06source\x18\x02 \x03(\t\x12-\n\x08interval\x18\x03 \x03(\x0b\x32\x1b.yuca.signal.SignalInterval\"\x80\x01\n\x04Unit\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08\x41\x43TIVITY\x10\x01\x12\x10\n\x0cGRAMS_OF_CO2\x10\x02\x12\n\n\x06JOULES\x10\x03\x12\x0b\n\x07JIFFIES\x10\x04\x12\t\n\x05HERTZ\x10\x05\x12\x0f\n\x0bNANOSECONDS\x10\x06\x12\t\n\x05WATTS\x10\x07\x12\x0b\n\x07\x43\x45LSIUS\x10\x08\x42\x07\n\x05_unit\"\x8c\x01\n\tComponent\x12\x1b\n\x0e\x63omponent_type\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x19\n\x0c\x63omponent_id\x18\x02 \x01(\tH\x01\x88\x01\x01\x12#\n\x06signal\x18\x03 \x03(\x0b\x32\x13.yuca.signal.SignalB\x11\n\x0f_component_typeB\x0f\n\r_component_id\"3\n\x06Report\x12)\n\tcomponent\x18\x01 \x03(\x0b\x32\x16.yuca.signal.ComponentB\x0f\n\x0byuca.signalP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'signal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013yuca.signalP\001'
  _globals['_SIGNALINTERVAL']._serialized_start=30
  _globals['_SIGNALINTERVAL']._serialized_end=487
  _globals['_SIGNALINTERVAL_TIMESTAMP']._serialized_start=218
  _globals['_SIGNALINTERVAL_TIMESTAMP']._serialized_end=287
  _globals['_SIGNALINTERVAL_SIGNALDATA']._serialized_start=290
  _globals['_SIGNALINTERVAL_SIGNALDATA']._serialized_end=469
  _globals['_SIGNALINTERVAL_SIGNALDATA_METADATA']._serialized_start=391
  _globals['_SIGNALINTERVAL_SIGNALDATA_METADATA']._serialized_end=459
  _globals['_SIGNAL']._serialized_start=490
  _globals['_SIGNAL']._serialized_end=746
  _globals['_SIGNAL_UNIT']._serialized_start=609
  _globals['_SIGNAL_UNIT']._serialized_end=737
  _globals['_COMPONENT']._serialized_start=749
  _globals['_COMPONENT']._serialized_end=889
  _globals['_REPORT']._serialized_start=891
  _globals['_REPORT']._serialized_end=942
# @@protoc_insertion_point(module_scope)
