java_library(
    name = "freq",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"], exclude=["Dvfs.java"]),
    deps = [
        "//src/yuca/src/main/java/yuca/util",
        "//src/yuca/src/main/proto/yuca/signal:signal_java_protos",
    ],
)
